export { login, register, getVerificationCode } from './auth'
export { getHomeData, getProductsByCategory, searchProducts, getProductDetail, getCategories } from './product'
export { getCartList, addToCart, updateCartAmount, deleteCartItem, batchDeleteCart } from './cart'
export { createOrderFromCart, buyNow, getOrderList, getOrderDetail, payOrder, cancelOrder, receiptOrder, updateRecipient, deleteOrder } from './order'
export { getUserInfo, updateUserInfo, uploadAvatar, getAvatar } from './user'
export { getImageUrl } from './product'
